apiVersion: apps/v1
kind: Deployment
metadata:
  name: annotation-service
  namespace: brainlens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: annotation-service
  template:
    metadata:
      labels:
        app: annotation-service
    spec:
      imagePullSecrets:
      - name: ecr-pull-secret
      containers:
      - name: annotation-service
        image: "{{ECR_REGISTRY}}/brainlens-annotation:latest"
        ports:
        - containerPort: 8003
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: brainlens-secrets
              key: mongo-connection-string
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8003"
        envFrom:
        - configMapRef:
            name: brainlens-config
        - secretRef:
            name: brainlens-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "150m"
        livenessProbe:
          httpGet:
            path: /api/v1/annotations/health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/annotations/health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: annotation-service
  namespace: brainlens
spec:
  selector:
    app: annotation-service
  ports:
  - port: 8003
    targetPort: 8003
  type: ClusterIP
