apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: brainlens
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      imagePullSecrets:
      - name: ecr-pull-secret
      containers:
      - name: frontend
        image: "{{ECR_REGISTRY}}/brainlens-frontend:latest"
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_BASE_URL
          value: "/api/v1"  # Use relative URL for same domain
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: brainlens
spec:
  selector:
    app: frontend-service
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP